services:
  sofia-trip-dev-ls0k0k4kowgc0gwskogsgc0s:
    build: .
    expose:
      - "3000"
    volumes:
      - sofia-trip-dev-data:/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - coolify
    labels:
      - "coolify.managed=true"
      - "coolify.type=application"
      - "traefik.enable=true"
      - "traefik.http.middlewares.gzip.compress=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.http-0-ls0k0k4kowgc0gwskogsgc0s.entryPoints=http"
      - "traefik.http.routers.http-0-ls0k0k4kowgc0gwskogsgc0s.middlewares=redirect-to-https"
      - "traefik.http.routers.http-0-ls0k0k4kowgc0gwskogsgc0s.rule=Host(\`sofia-trip-dev.forge.dexmind.ai\`) && PathPrefix(\`/\`)"
      - "traefik.http.routers.http-0-ls0k0k4kowgc0gwskogsgc0s.service=http-0-ls0k0k4kowgc0gwskogsgc0s"
      - "traefik.http.routers.https-0-ls0k0k4kowgc0gwskogsgc0s.entryPoints=https"
      - "traefik.http.routers.https-0-ls0k0k4kowgc0gwskogsgc0s.middlewares=gzip"
      - "traefik.http.routers.https-0-ls0k0k4kowgc0gwskogsgc0s.rule=Host(\`sofia-trip-dev.forge.dexmind.ai\`) && PathPrefix(\`/\`)"
      - "traefik.http.routers.https-0-ls0k0k4kowgc0gwskogsgc0s.service=https-0-ls0k0k4kowgc0gwskogsgc0s"
      - "traefik.http.routers.https-0-ls0k0k4kowgc0gwskogsgc0s.tls=true"
      - "traefik.http.routers.https-0-ls0k0k4kowgc0gwskogsgc0s.tls.certresolver=letsencrypt"
      - "traefik.http.services.http-0-ls0k0k4kowgc0gwskogsgc0s.loadbalancer.server.port=3000"
      - "traefik.http.services.https-0-ls0k0k4kowgc0gwskogsgc0s.loadbalancer.server.port=3000"

volumes:
  sofia-trip-dev-data:
    name: ls0k0k4kowgc0gwskogsgc0s_sofia-trip-dev-data

networks:
  coolify:
    external: true
